import assert from "node:assert/strict"
import { describe, it } from "node:test"

import type { AgentThreadMessage } from "../../../src/features/agent-message/agent-message-data.ts"
import {
  compactSummaryBody,
  foldCommandSurfaces,
  isClearCommandUserMessage,
  isCompactCommandUserMessage,
  userMessageSurface,
} from "../../../src/features/agent-message/slash-command-envelope.ts"

const CLEAR_ENVELOPE =
  "<command-name>/clear</command-name>\n            <command-message>clear</command-message>\n            <command-args></command-args>"

const COMPACT_ENVELOPE =
  "<command-name>/compact</command-name>\n            <command-message>compact</command-message>\n            <command-args></command-args>"

const COMPACT_SUMMARY = `This session is being continued from a previous conversation that ran out of context. The summary below covers the earlier portion of the conversation.

Summary:
1. Primary Request and Intent:
   - Write a mock SRE dashboard.`

function message(
  id: string,
  role: AgentThreadMessage["role"],
  content: string,
  status: AgentThreadMessage["status"] = "complete"
): AgentThreadMessage {
  return {
    id,
    role,
    content,
    createdAt: "2026-08-28T14:58:47.000Z",
    status,
  }
}

describe("isClearCommandUserMessage", () => {
  it("matches the Claude clear envelope in either tag order", () => {
    assert.equal(isClearCommandUserMessage(CLEAR_ENVELOPE), true)
    assert.equal(
      isClearCommandUserMessage(
        "<command-message>clear</command-message>\n<command-name>/clear</command-name>\n<command-args></command-args>"
      ),
      true
    )
  })

  it("matches a live /clear send payload", () => {
    assert.equal(isClearCommandUserMessage("/clear"), true)
    assert.equal(isClearCommandUserMessage("/clear  "), true)
  })

  it("does not match other commands or ordinary text", () => {
    assert.equal(isClearCommandUserMessage("clear the session"), false)
    assert.equal(isClearCommandUserMessage(COMPACT_ENVELOPE), false)
    assert.equal(
      isClearCommandUserMessage(
        "<command-name>/loop</command-name>\n<command-message>loop</command-message>\n<command-args>1m</command-args>"
      ),
      false
    )
  })
})

describe("isCompactCommandUserMessage", () => {
  it("matches the Claude compact envelope from session 53aaa966", () => {
    assert.equal(isCompactCommandUserMessage(COMPACT_ENVELOPE), true)
    assert.equal(
      isCompactCommandUserMessage(
        "<command-message>compact</command-message>\n<command-name>/compact</command-name>\n<command-args>keep the dashboard</command-args>"
      ),
      true
    )
  })

  it("matches a live /compact send payload with optional args", () => {
    assert.equal(isCompactCommandUserMessage("/compact"), true)
    assert.equal(isCompactCommandUserMessage("/compact keep files"), true)
  })

  it("does not match clear or ordinary text", () => {
    assert.equal(isCompactCommandUserMessage(CLEAR_ENVELOPE), false)
    assert.equal(isCompactCommandUserMessage("please compact this"), false)
  })
})

describe("userMessageSurface", () => {
  it("maps clear and compact envelopes to markers", () => {
    assert.equal(userMessageSurface(CLEAR_ENVELOPE), "session-reset")
    assert.equal(userMessageSurface(COMPACT_ENVELOPE), "conversation-compacted")
    assert.equal(userMessageSurface("/compact"), "conversation-compacted")
  })

  it("hides compact stdout, caveat, and continuation summary", () => {
    assert.equal(
      userMessageSurface("<local-command-stdout>Compacted </local-command-stdout>"),
      "hidden"
    )
    assert.equal(
      userMessageSurface(
        "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>"
      ),
      "hidden"
    )
    assert.equal(userMessageSurface(COMPACT_SUMMARY), "hidden")
  })

  it("keeps ordinary user text as a bubble", () => {
    assert.equal(userMessageSurface("写一个mock 的sre 大盘"), "bubble")
  })
})

describe("compactSummaryBody", () => {
  it("strips the continuation boilerplate and keeps the summary", () => {
    assert.equal(
      compactSummaryBody(COMPACT_SUMMARY),
      "1. Primary Request and Intent:\n   - Write a mock SRE dashboard."
    )
  })
})

describe("foldCommandSurfaces", () => {
  it("keeps compacting while the placeholder assistant is still open", () => {
    const compact = message("c1", "user", "/compact")
    const working = message("a1", "assistant", "", "streaming")
    const folded = foldCommandSurfaces([compact, working])

    assert.equal(folded.length, 1)
    assert.equal(folded[0]?.compact?.phase, "compacting")
    assert.equal(folded[0]?.compact?.summary, undefined)
  })

  it("stays compacting after the empty assistant settles and before the summary arrives", () => {
    const compact = message("c1", "user", "/compact")
    const empty = message("a1", "assistant", "")
    const folded = foldCommandSurfaces([compact, empty])

    assert.equal(folded.length, 1)
    assert.equal(folded[0]?.compact?.phase, "compacting")
  })

  it("hides the synthetic No response requested assistant", () => {
    const compact = message("c1", "user", "/compact")
    const synthetic = message("a1", "assistant", "No response requested.")
    const folded = foldCommandSurfaces([compact, synthetic])

    assert.equal(folded.length, 1)
    assert.equal(folded[0]?.id, "c1")
    assert.equal(folded[0]?.compact?.phase, "compacting")
  })

  it("pairs a nearby continuation summary and marks the compact done", () => {
    const summary = message("s1", "user", COMPACT_SUMMARY)
    const compact = message("c1", "user", COMPACT_ENVELOPE)
    const stdout = message(
      "o1",
      "user",
      "<local-command-stdout>Compacted </local-command-stdout>"
    )
    const folded = foldCommandSurfaces([summary, compact, stdout])

    assert.equal(folded.length, 1)
    assert.equal(folded[0]?.id, "c1")
    assert.equal(folded[0]?.compact?.phase, "compacted")
    assert.equal(
      folded[0]?.compact?.summary,
      "1. Primary Request and Intent:\n   - Write a mock SRE dashboard."
    )
  })
})
