import Prism from "prismjs"
import "prismjs/components/prism-bash"
import "prismjs/components/prism-c"
import "prismjs/components/prism-cmake"
import "prismjs/components/prism-coffeescript"
import "prismjs/components/prism-cpp"
import "prismjs/components/prism-editorconfig"
import "prismjs/components/prism-go"
import "prismjs/components/prism-graphql"
import "prismjs/components/prism-ignore"
import "prismjs/components/prism-ini"
import "prismjs/components/prism-json"
import "prismjs/components/prism-kotlin"
import "prismjs/components/prism-makefile"
import "prismjs/components/prism-markdown"
import "prismjs/components/prism-n4js"
import "prismjs/components/prism-objectivec"
import "prismjs/components/prism-properties"
import "prismjs/components/prism-python"
import "prismjs/components/prism-reason"
import "prismjs/components/prism-regex"
import "prismjs/components/prism-rust"
import "prismjs/components/prism-sql"
import "prismjs/components/prism-swift"
import "prismjs/components/prism-typescript"
import "prismjs/components/prism-jsx"
import "prismjs/components/prism-tsx"
import "prismjs/components/prism-yaml"
import "prismjs/components/prism-docker"

export { Prism }
